const pageCanvas=document.querySelector('#page-embers');
if(pageCanvas){const pageCtx=pageCanvas.getContext('2d');let sparks=[];function sizePageCanvas(){pageCanvas.width=innerWidth*devicePixelRatio;pageCanvas.height=innerHeight*devicePixelRatio;pageCanvas.style.width=`${innerWidth}px`;pageCanvas.style.height=`${innerHeight}px`;pageCtx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);sparks=Array.from({length:Math.min(55,Math.floor(innerWidth/24))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.2+.3,a:Math.random()*.4+.08,s:Math.random()*.22+.05}))}function paint(){pageCtx.clearRect(0,0,innerWidth,innerHeight);sparks.forEach(p=>{pageCtx.fillStyle=`rgba(224,103,43,${p.a})`;pageCtx.beginPath();pageCtx.arc(p.x,p.y,p.r,0,Math.PI*2);pageCtx.fill();p.y-=p.s;if(p.y<0)p.y=innerHeight});requestAnimationFrame(paint)}addEventListener('resize',sizePageCanvas);sizePageCanvas();paint()}
const pageObserver=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('visible',e.isIntersecting)),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>pageObserver.observe(e));
document.querySelectorAll('[data-year]').forEach(e=>e.textContent=new Date().getFullYear());
const extraStyle=document.createElement('link');extraStyle.rel='stylesheet';extraStyle.href='subpages.css';document.head.appendChild(extraStyle);
const brand=document.querySelector('.page-header .brand');if(brand){const menu=document.createElement('button');menu.className='subpage-menu';menu.type='button';menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');menu.textContent='☰';brand.after(menu);const nav=document.querySelector('.page-header nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('is-open');menu.setAttribute('aria-expanded',String(open))})}
const roadQuotes=['“I’ve met coffins with more warmth in them.”','“Not without ale.”','“You’re tighter than a dwarf’s coin purse on tax day.”','“Almost feels rude to spoil it by surviving the night.”','“That looks older than a witch’s mole.”','“If dwarves built it, you can bet they didn’t want it found.”'];let roadBag=[];const roadQuote=document.querySelector('#road-quote');const roadButton=document.querySelector('#another-road-round');if(roadButton)roadButton.addEventListener('click',()=>{if(!roadBag.length)roadBag=[...roadQuotes].sort(()=>Math.random()-.5);roadQuote.textContent=roadBag.pop()});
const completion=document.querySelector('#adventure-completion');if(completion){try{const save=JSON.parse(localStorage.getItem('embervoid-ruins-save-v2'));if(save?.ended){const lines={memoryEnd:'Not the worst choice a human ever made.',flameEnd:'Now you’ve touched something you don’t understand.',goldEnd:'Finally, an explorer with sensible priorities.',darkEnd:'Empty-handed is still better than dead.',defeat:'I told you the statue was built to keep fools out.'};completion.hidden=false;completion.innerHTML=`<strong>Bhalmuck disputes your account.</strong>“${lines[save.scene]||'Aye, I heard what happened. That is not how I remember it.'}”`;}}catch{}}
const currentPage=(location.pathname.split('/').pop()||'index.html').replace('.html','');const depthByPage={book:1,world:2,calendar:3,gods:3,origins:3,archive:4,road:4,adventures:5,adventure:5,about:2};const depth=depthByPage[currentPage]||1;document.body.dataset.depth=depth;document.body.dataset.page=currentPage;document.documentElement.style.setProperty('--void-depth',depth);
let remembered=[];try{remembered=JSON.parse(localStorage.getItem('embervoid-pages')||'[]')}catch{}const visited=new Set(remembered);visited.add(currentPage);localStorage.setItem('embervoid-pages',JSON.stringify([...visited]));
const presence=document.createElement('div');presence.className='void-presence';presence.setAttribute('aria-hidden','true');presence.innerHTML='<div class="void-glyphs">⟡ ᚷ ⋮ ᛉ ◇\n  ᛏ ⟟ ⟁ ᚾ ⋮\n◇ ᚱ ⟡ ᛃ ⟁</div><div class="void-watcher"></div><div class="void-eyes"></div><div class="void-orb"></div>';document.body.prepend(presence);
const whispers=['The path remembers you.','Some doors open inward.','You have seen this mark before.','The silence is not empty.','It has moved closer.'];const whisper=document.createElement('p');whisper.className='void-whisper';whisper.textContent=whispers[Math.min(whispers.length-1,Math.max(depth-1,visited.size-2))];document.body.appendChild(whisper);setTimeout(()=>whisper.classList.add('heard'),1800);setTimeout(()=>whisper.classList.remove('heard'),7800);
if(currentPage==='road'){const wisdom=document.querySelector('.road-wisdom');if(wisdom){const tankard=document.createElement('div');tankard.className='road-tankard';tankard.setAttribute('aria-hidden','true');wisdom.prepend(tankard)}}
